version: "2"
services:
  db:
    image: mongo
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    container_name: db
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    # command: bash -c "rm -rf ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    container_name: web
    tty: true
    volumes:
      - .:/server
    ports:
      - 3000:3000
    depends_on:
      - db
