FROM ruby:2.4.2
RUN apt-get update -qq
RUN apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs

RUN mkdir /it4996
WORKDIR /it4996

ADD Gemfile /it4996/Gemfile
ADD Gemfile.lock /it4996/Gemfile.lock
RUN bundle install

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g yarn
RUN yarn install

ADD . /it4996
