version: "2"
services:
  db:
    image: mongo
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    container_name: db
  # redis:
  #   image: redis
  #   ports:
  #     - "6479:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    # command: bundle exec rails s -p 3000 -b "0.0.0.0"
    container_name: web
    tty: true
    volumes:
      - .:/it4996
    ports:
      - 3333:3333
    depends_on:
      - db
      # - redis
